HTML-+-CSS-+-ES6-+-Spring-Cleaning
cs-24-sw-2-p2-05/team-cohesion-tool pull request #9
Opened 2024-04-09 07:59 UTC by Naitsabot

Too much
but it works

2024-04-09 08:04 UTC, soupglasses requested changes

2024-04-09 08:04 UTC, soupglasses commented on src/main.mjs
> +// So that a "get" does not have to be create for every file in the public directory.
Dont quote get, maybe rephrase to GET to show its a html GET. Or call it instead a "get request".

2024-04-09 08:04 UTC, soupglasses commented on src/main.mjs
> +//****************************************************************
Project wide: Maybe lets not use this commenting style. Its excessively verbose for what ends up being often one line comments.

2024-04-09 08:26 UTC, soupglasses approved these changes

2024-04-09 08:26 UTC, merged

2024-04-09 10:07 UTC, soupglasses commented
Closes #3

2024-04-10 10:14 UTC, JakobTopholt commented
You can setup auto closing of issues related to pull requests if the pull request is based on the issue.

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue